services:
  solr:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mscat-solr
    ports:
      - 8983:8983
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
      SOLR_MODULES: "analysis-extras"
    volumes:
      - ./external-vol:/var/solr
